from pathlib import Path

root = Path('V2rayNG/app/src/main')

# Main layout: make supplied artwork fill both FABs.
p = root / 'res/layout/activity_main.xml'
s = p.read_text()
s = s.replace('''                        android:focusable="true"\n                        android:src="@drawable/ic_play_24dp"\n                        app:backgroundTint="@android:color/white"\n                        app:fabCustomSize="172dp"\n                        app:maxImageSize="64dp"\n                        app:shapeAppearanceOverlay="@style/MobileTinaCircleFab"\n                        app:tint="#202124" />''', '''                        android:focusable="true"\n                        android:padding="0dp"\n                        android:scaleType="centerCrop"\n                        android:src="@drawable/mt_auto_white"\n                        app:backgroundTint="@android:color/transparent"\n                        app:fabCustomSize="172dp"\n                        app:maxImageSize="172dp"\n                        app:shapeAppearanceOverlay="@style/MobileTinaCircleFab" />''', 1)
s = s.replace('''                        android:contentDescription="@string/tasker_start_service"\n                        android:src="@drawable/ic_play_24dp"\n                        app:fabCustomSize="58dp"\n                        app:maxImageSize="27dp"\n                        app:shapeAppearanceOverlay="@style/MobileTinaCircleFab"\n                        app:tint="@color/colorWhite" />''', '''                        android:contentDescription="@string/tasker_start_service"\n                        android:padding="0dp"\n                        android:scaleType="centerCrop"\n                        android:src="@drawable/mt_manual_stop"\n                        app:backgroundTint="@android:color/transparent"\n                        app:fabCustomSize="58dp"\n                        app:maxImageSize="58dp"\n                        app:shapeAppearanceOverlay="@style/MobileTinaCircleFab" />''', 1)
p.write_text(s)

# Drawer header: replace legacy text/header artwork with supplied nav image.
p = root / 'res/layout/nav_header.xml'
p.write_text('''<?xml version="1.0" encoding="utf-8"?>\n<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"\n    android:layout_width="match_parent"\n    android:layout_height="176dp"\n    android:background="#000000"\n    android:padding="8dp">\n\n    <ImageView\n        android:layout_width="match_parent"\n        android:layout_height="match_parent"\n        android:adjustViewBounds="true"\n        android:contentDescription="@string/mobiletina_app_name"\n        android:scaleType="fitCenter"\n        android:src="@drawable/mt_nav" />\n\n</FrameLayout>\n''')

# Main activity: swap artwork by actual connection state, with no tint/background.
p = root / 'java/com/v2ray/ang/ui/MainActivity.kt'
s = p.read_text()
old = '''        val autoBackground: Int\n        val autoTint: Int\n        val autoIcon: Int\n        val status: String\n        when {\n            running -> {\n                autoBackground = Color.rgb(25, 118, 210)\n                autoTint = Color.WHITE\n                autoIcon = R.drawable.ic_stop_24dp\n                status = getString(R.string.mobiletina_status_connected)\n            }\n            smartConnecting -> {\n                autoBackground = Color.rgb(255, 193, 7)\n                autoTint = Color.rgb(61, 48, 0)\n                autoIcon = R.drawable.ic_fab_check\n                status = getString(R.string.mobiletina_status_connecting)\n            }\n            smartConnectionFailed -> {\n                autoBackground = Color.rgb(211, 47, 47)\n                autoTint = Color.WHITE\n                autoIcon = R.drawable.ic_fab_check\n                status = getString(R.string.mobiletina_status_failed)\n            }\n            else -> {\n                autoBackground = Color.WHITE\n                autoTint = Color.rgb(32, 33, 36)\n                autoIcon = R.drawable.ic_play_24dp\n                status = getString(R.string.mobiletina_status_disconnected)\n            }\n        }\n\n        binding.fabAuto.backgroundTintList = ColorStateList.valueOf(autoBackground)\n        binding.fabAuto.imageTintList = ColorStateList.valueOf(autoTint)\n        binding.fabAuto.setImageResource(autoIcon)\n'''
new = '''        val autoArtwork: Int\n        val status: String\n        when {\n            running -> {\n                autoArtwork = R.drawable.mt_auto_blue\n                status = getString(R.string.mobiletina_status_connected)\n            }\n            smartConnecting -> {\n                autoArtwork = R.drawable.mt_auto_yellow\n                status = getString(R.string.mobiletina_status_connecting)\n            }\n            smartConnectionFailed -> {\n                autoArtwork = R.drawable.mt_auto_red\n                status = getString(R.string.mobiletina_status_failed)\n            }\n            else -> {\n                autoArtwork = R.drawable.mt_auto_white\n                status = getString(R.string.mobiletina_status_disconnected)\n            }\n        }\n\n        binding.fabAuto.backgroundTintList = ColorStateList.valueOf(Color.TRANSPARENT)\n        binding.fabAuto.imageTintList = null\n        binding.fabAuto.setImageResource(autoArtwork)\n'''
if old not in s:
    raise SystemExit('Auto FAB state block not found')
s = s.replace(old, new, 1)
old_manual = '''        binding.fab.setImageResource(if (running) R.drawable.ic_stop_24dp else R.drawable.ic_play_24dp)\n        binding.fab.backgroundTintList = ColorStateList.valueOf(\n            when {\n                running -> ContextCompat.getColor(this, R.color.color_fab_active)\n                manualConnecting -> Color.rgb(255, 193, 7)\n                else -> ContextCompat.getColor(this, R.color.color_fab_inactive)\n            }\n        )\n'''
new_manual = '''        binding.fab.backgroundTintList = ColorStateList.valueOf(Color.TRANSPARENT)\n        binding.fab.imageTintList = null\n        // User-supplied artwork: VPN off = stop, VPN on = fab.\n        binding.fab.setImageResource(\n            if (running) R.drawable.mt_manual_fab else R.drawable.mt_manual_stop\n        )\n'''
if old_manual not in s:
    raise SystemExit('Manual FAB state block not found')
s = s.replace(old_manual, new_manual, 1)
p.write_text(s)

print('MobileTina supplied artwork integrated')
